### ISSUE TITLE
Hex doesn't support the same colors as sRGB

### ISSUE THREAD

**Issue by steadicat** [boronine/colorspaces.js#8]
There are many colors that convert fine from CIELCHuv to sRGB, but throw an `Illegal sRGB value` when converted to hex. For example:

```JS
> var colorspaces = require('colorspaces');
> var srgb = colorspaces.converter('CIELCHuv', 'sRGB');
> srgb([40, 90, 50]);
[ 0.5574086227634354, 0.3190888837593599, -0.8073410043455771 ]
> var hex = colorspaces.converter('CIELCHuv', 'hex');
> hex([40, 90, 50]);
Error: Illegal sRGB value
    at sRGB_prepare (./node_modules/colorspaces/colorspaces.js:235:15)
    at Object.conv.sRGB.hex (./node_modules/colorspaces/colorspaces.js:249:13)
    at ./node_modules/colorspaces/colorspaces.js:294:37
    at ./node_modules/colorspaces/colorspaces.js:288:18
    at repl:1:1
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
```

**Comment by boronine** [comment]
The problem here is that `[40, 90, 50]` is not a valid CIELCHuv color. This is evident from the negative RGB blue value. We are not throwing an exception when converting to sRGB because sometimes rounding errors can make a valid color generate an RGB value just below zero (-0.000000001).
